name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, merge-syntax ]

jobs:
  test-syntax:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Cache OCaml's opam
      uses: actions/cache@v2.1.5
      with:
        path: ~/.opam
        key: macos-latest-ocaml-4.06.1

    - name: Use OCaml
      uses: ocaml/setup-ocaml@v1
      with:
        ocaml-version: 4.06.1

    - name: Use Node.js
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.4.0

    - name: Install depedencies
      working-directory: ./syntax
      run: npm ci

    - name: Run tests
      working-directory: ./syntax
      run: eval $(opam env) && make roundtrip-test
